extension String {

    var imageName: String {
        switch self {
        case "SelfCheck":                           return "pencil.line"
        case "Weight":                              return "speedometer"
        case "Steps":                               return "figure.walk"

            //MARK: - workout
        case "American Football":                   return "figure.american.football"
        case "Archery":                             return "figure.archery"
        case "Australian Football":                 return "figure.australian.football"
        case "Badminton":                           return "figure.badminton"
        case "Baseball":                            return "figure.baseball"
        case "Basketball":                          return "figure.basketball"
        case "Bowling":                             return "figure.bowling"
        case "Boxing":                              return "figure.boxing"
        case "Climbing":                            return "figure.climbing"
        case "Cross Training":                      return "figure.cross.training"
        case "Curling":                             return "figure.curling"
        case "Cycling":                             return "figure.outdoor.cycle"
        case "Dance":                               return "figure.dance"
        case "Dance Inspired Training":             return "figure.dance"
        case "Elliptical":                          return "figure.elliptical"
        case "Equestrian Sports":                   return "figure.equestrian.sports"
        case "Fencing":                             return "figure.fencing"
        case "Fishing":                             return "figure.fishing"
        case "Functional Strength Training":        return "figure.strengthtraining.functional"
        case "Golf":                                return "figure.golf"
        case "Gymnastics":                          return "figure.gymnastics"
        case "Handball":                            return "figure.handball"
        case "Hiking":                              return "figure.hiking"
        case "Hockey":                              return "figure.hockey"
        case "Hunting":                             return "figure.hunting"
        case "Lacrosse":                            return "figure.lacrosse"
        case "Martial Arts":                        return "figure.martial.arts"
        case "Mind and Body":                       return "figure.mind.and.body"
        case "Play":                                return "figure.play"
        case "Racquetball":                         return "figure.racquetball"
        case "Rowing":                              return "figure.rower"
        case "Rugby":                               return "figure.rugby"
        case "Running":                             return "figure.run"
        case "Sailing":                             return "figure.sailing"
        case "Skating Sports":                      return "figure.skating"
        case "Snow Sports":                         return "figure.snowboarding"
        case "Soccer":                              return "figure.soccer"
        case "Softball":                            return "figure.softball"
        case "Squash":                              return "figure.squash"
        case "Stair Climbing":                      return "figure.climbing"
        case "Surfing Sports":                      return "figure.surfing"
        case "Swimming":                            return "figure.pool.swim"
        case "Table Tennis":                        return "figure.table.tennis"
        case "Tennis":                              return "figure.tennis"
        case "Track and Field":                     return "figure.track.and.field"
        case "Traditional Strength Training":       return "figure.strengthtraining.traditional"
        case "Volleyball":                          return "figure.volleyball"
        case "Walking":                             return "figure.walk"
        case "Water Fitness":                       return "figure.water.fitness"
        case "Water Polo":                          return "figure.waterpolo"
        case "Water Sports":                        return "figure.pool.swim"
        case "Wrestling":                           return "figure.wrestling"
        case "Yoga":                                return "figure.yoga"

            //iOS 10
        case "Barre":                               return "figure.barre"
        case "Core Training":                       return "figure.core.training"
        case "Cross Country Skiing":                return "figure.skiing.crosscountry"
        case "Downhill Skiing":                     return "figure.skiing.downhill"
        case "Flexibility":                         return "figure.flexibility"
        case "High Intensity Interval Training":    return "figure.highintensity.intervaltraining"
        case "Jump Rope":                           return "figure.jumprope"
        case "Kickboxing":                          return "figure.kickboxing"
        case "Pilates":                             return "figure.pilates"
        case "Snowboarding":                        return "figure.snowboarding"
        case "Stairs":                              return "figure.stairs"
        case "Step Training":                       return "figure.step.training"
        case "Wheelchair Walk Pace":                return "figure.roll"
        case "Wheelchair Run Pace":                 return "figure.roll.runningpace"

            //iOS 11
        case "Tai Chi":                             return "figure.taichi"
        case "Mixed Cardio":                        return "figure.mixed.cardio"
        case "Hand Cycling":                        return "figure.hand.cycling"

            //iOS 13
        case "Disc Sports":                         return "figure.disc.sports"
        case "Fitness Gaming":                      return "trophy"

            // Catch-all
        default:                                    return "figure.mixed.cardio"
        }
    }
}
